name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 87.107.68.229
        port: 22
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /srv/miladrahimi.github.io
          git reset --hard HEAD^
          git pull
